-- Migration 009: Seed 50 Mumbai paramedics into ambulance_attendants
-- Passwords (bcrypt cost 12):
--   paramedic123 → $2b$12$ashv3XcnuBHcPVRebGUeq.sZAsTGoBFBN3Fl8QnrM/rQT8ZBCVqeG
--   rescue456    → $2b$12$2VUapdTbeoNB4hFuZnOjV.sw0f2NXehcZoJ5E/ls8/2GvsY3rx.g.
-- See db/seeds/mumbai_paramedics.csv for the full credential sheet (plain-text passwords).
-- All paramedics are based in Mumbai, Maharashtra.

INSERT INTO ambulance_attendants (badge_id, password_hash, name, callsign, assigned_ambulance_id, email) VALUES
('PARA-101', '$2b$12$ashv3XcnuBHcPVRebGUeq.sZAsTGoBFBN3Fl8QnrM/rQT8ZBCVqeG', 'Ravi Kumar (EMT)',            'Alpha-205 (BLS Unit)',    'amb-205', 'ravi.kumar@crisiscare.in'),
('PARA-102', '$2b$12$ashv3XcnuBHcPVRebGUeq.sZAsTGoBFBN3Fl8QnrM/rQT8ZBCVqeG', 'Sunita Sharma (Paramedic)',   'Bravo-301 (ALS Unit)',    'amb-301', 'sunita.sharma@crisiscare.in'),
('PARA-103', '$2b$12$2VUapdTbeoNB4hFuZnOjV.sw0f2NXehcZoJ5E/ls8/2GvsY3rx.g.', 'Arjun Nair (EMT)',            'Charlie-102 (BLS Unit)',  'amb-102', 'arjun.nair@crisiscare.in'),
('PARA-104', '$2b$12$2VUapdTbeoNB4hFuZnOjV.sw0f2NXehcZoJ5E/ls8/2GvsY3rx.g.', 'Priya Desai (Paramedic Lead)','Delta-410 (ALS Unit)',    'amb-410', 'priya.desai@crisiscare.in'),
('PARA-105', '$2b$12$ashv3XcnuBHcPVRebGUeq.sZAsTGoBFBN3Fl8QnrM/rQT8ZBCVqeG', 'Vivek Patil (EMT)',           'Echo-207 (BLS Unit)',     'amb-207', 'vivek.patil@crisiscare.in'),
('PARA-106', '$2b$12$ashv3XcnuBHcPVRebGUeq.sZAsTGoBFBN3Fl8QnrM/rQT8ZBCVqeG', 'Meera Joshi (Paramedic)',     'Foxtrot-315 (ALS Unit)',  'amb-315', 'meera.joshi@crisiscare.in'),
('PARA-107', '$2b$12$2VUapdTbeoNB4hFuZnOjV.sw0f2NXehcZoJ5E/ls8/2GvsY3rx.g.', 'Rohit Kulkarni (EMT)',        'Golf-118 (BLS Unit)',     'amb-118', 'rohit.kulkarni@crisiscare.in'),
('PARA-108', '$2b$12$2VUapdTbeoNB4hFuZnOjV.sw0f2NXehcZoJ5E/ls8/2GvsY3rx.g.', 'Kavya Iyer (Paramedic)',      'Hotel-422 (ALS Unit)',    'amb-422', 'kavya.iyer@crisiscare.in'),
('PARA-109', '$2b$12$ashv3XcnuBHcPVRebGUeq.sZAsTGoBFBN3Fl8QnrM/rQT8ZBCVqeG', 'Sanjay Mehta (EMT)',          'India-211 (BLS Unit)',    'amb-211', 'sanjay.mehta@crisiscare.in'),
('PARA-110', '$2b$12$ashv3XcnuBHcPVRebGUeq.sZAsTGoBFBN3Fl8QnrM/rQT8ZBCVqeG', 'Divya Rao (Paramedic)',       'Juliet-319 (ALS Unit)',   'amb-319', 'divya.rao@crisiscare.in'),
('PARA-111', '$2b$12$2VUapdTbeoNB4hFuZnOjV.sw0f2NXehcZoJ5E/ls8/2GvsY3rx.g.', 'Aditya Pillai (EMT)',         'Kilo-124 (BLS Unit)',     'amb-124', 'aditya.pillai@crisiscare.in'),
('PARA-112', '$2b$12$2VUapdTbeoNB4hFuZnOjV.sw0f2NXehcZoJ5E/ls8/2GvsY3rx.g.', 'Lakshmi Menon (Paramedic)',   'Lima-428 (ALS Unit)',     'amb-428', 'lakshmi.menon@crisiscare.in'),
('PARA-113', '$2b$12$ashv3XcnuBHcPVRebGUeq.sZAsTGoBFBN3Fl8QnrM/rQT8ZBCVqeG', 'Nikhil Sawant (EMT)',         'Mike-215 (BLS Unit)',     'amb-215', 'nikhil.sawant@crisiscare.in'),
('PARA-114', '$2b$12$ashv3XcnuBHcPVRebGUeq.sZAsTGoBFBN3Fl8QnrM/rQT8ZBCVqeG', 'Rashmi Godse (Paramedic)',    'November-323 (ALS Unit)', 'amb-323', 'rashmi.godse@crisiscare.in'),
('PARA-115', '$2b$12$2VUapdTbeoNB4hFuZnOjV.sw0f2NXehcZoJ5E/ls8/2GvsY3rx.g.', 'Karan Bhosle (EMT)',          'Oscar-130 (BLS Unit)',    'amb-130', 'karan.bhosle@crisiscare.in'),
('PARA-116', '$2b$12$2VUapdTbeoNB4hFuZnOjV.sw0f2NXehcZoJ5E/ls8/2GvsY3rx.g.', 'Anjali Wagh (Paramedic)',     'Papa-434 (ALS Unit)',     'amb-434', 'anjali.wagh@crisiscare.in'),
('PARA-117', '$2b$12$ashv3XcnuBHcPVRebGUeq.sZAsTGoBFBN3Fl8QnrM/rQT8ZBCVqeG', 'Sachin Gaikwad (EMT)',        'Quebec-219 (BLS Unit)',   'amb-219', 'sachin.gaikwad@crisiscare.in'),
('PARA-118', '$2b$12$ashv3XcnuBHcPVRebGUeq.sZAsTGoBFBN3Fl8QnrM/rQT8ZBCVqeG', 'Pooja Shetty (Paramedic)',    'Romeo-327 (ALS Unit)',    'amb-327', 'pooja.shetty@crisiscare.in'),
('PARA-119', '$2b$12$2VUapdTbeoNB4hFuZnOjV.sw0f2NXehcZoJ5E/ls8/2GvsY3rx.g.', 'Amol Pawar (EMT)',            'Sierra-136 (BLS Unit)',   'amb-136', 'amol.pawar@crisiscare.in'),
('PARA-120', '$2b$12$2VUapdTbeoNB4hFuZnOjV.sw0f2NXehcZoJ5E/ls8/2GvsY3rx.g.', 'Snehal Chavan (Paramedic)',   'Tango-440 (ALS Unit)',    'amb-440', 'snehal.chavan@crisiscare.in'),
('PARA-121', '$2b$12$ashv3XcnuBHcPVRebGUeq.sZAsTGoBFBN3Fl8QnrM/rQT8ZBCVqeG', 'Gaurav Mane (EMT)',           'Uniform-223 (BLS Unit)',  'amb-223', 'gaurav.mane@crisiscare.in'),
('PARA-122', '$2b$12$ashv3XcnuBHcPVRebGUeq.sZAsTGoBFBN3Fl8QnrM/rQT8ZBCVqeG', 'Deepa Naik (Paramedic)',      'Victor-331 (ALS Unit)',   'amb-331', 'deepa.naik@crisiscare.in'),
('PARA-123', '$2b$12$2VUapdTbeoNB4hFuZnOjV.sw0f2NXehcZoJ5E/ls8/2GvsY3rx.g.', 'Omkar Shinde (EMT)',          'Whiskey-142 (BLS Unit)',  'amb-142', 'omkar.shinde@crisiscare.in'),
('PARA-124', '$2b$12$2VUapdTbeoNB4hFuZnOjV.sw0f2NXehcZoJ5E/ls8/2GvsY3rx.g.', 'Shruti Dalvi (Paramedic)',    'Xray-446 (ALS Unit)',     'amb-446', 'shruti.dalvi@crisiscare.in'),
('PARA-125', '$2b$12$ashv3XcnuBHcPVRebGUeq.sZAsTGoBFBN3Fl8QnrM/rQT8ZBCVqeG', 'Ajay Marathe (EMT)',          'Yankee-227 (BLS Unit)',   'amb-227', 'ajay.marathe@crisiscare.in'),
('PARA-126', '$2b$12$ashv3XcnuBHcPVRebGUeq.sZAsTGoBFBN3Fl8QnrM/rQT8ZBCVqeG', 'Neeta Karande (Paramedic)',   'Zulu-335 (ALS Unit)',     'amb-335', 'neeta.karande@crisiscare.in'),
('PARA-127', '$2b$12$2VUapdTbeoNB4hFuZnOjV.sw0f2NXehcZoJ5E/ls8/2GvsY3rx.g.', 'Suresh Jadhav (EMT)',         'Alpha-148 (BLS Unit)',    'amb-148', 'suresh.jadhav@crisiscare.in'),
('PARA-128', '$2b$12$2VUapdTbeoNB4hFuZnOjV.sw0f2NXehcZoJ5E/ls8/2GvsY3rx.g.', 'Pallavi Landge (Paramedic)',  'Bravo-452 (ALS Unit)',    'amb-452', 'pallavi.landge@crisiscare.in'),
('PARA-129', '$2b$12$ashv3XcnuBHcPVRebGUeq.sZAsTGoBFBN3Fl8QnrM/rQT8ZBCVqeG', 'Mahesh Tiwari (EMT)',         'Charlie-231 (BLS Unit)',  'amb-231', 'mahesh.tiwari@crisiscare.in'),
('PARA-130', '$2b$12$ashv3XcnuBHcPVRebGUeq.sZAsTGoBFBN3Fl8QnrM/rQT8ZBCVqeG', 'Varsha Borse (Paramedic)',    'Delta-339 (ALS Unit)',    'amb-339', 'varsha.borse@crisiscare.in'),
('PARA-131', '$2b$12$2VUapdTbeoNB4hFuZnOjV.sw0f2NXehcZoJ5E/ls8/2GvsY3rx.g.', 'Nitin Kamble (EMT)',          'Echo-154 (BLS Unit)',     'amb-154', 'nitin.kamble@crisiscare.in'),
('PARA-132', '$2b$12$2VUapdTbeoNB4hFuZnOjV.sw0f2NXehcZoJ5E/ls8/2GvsY3rx.g.', 'Gauri Salve (Paramedic)',     'Foxtrot-458 (ALS Unit)',  'amb-458', 'gauri.salve@crisiscare.in'),
('PARA-133', '$2b$12$ashv3XcnuBHcPVRebGUeq.sZAsTGoBFBN3Fl8QnrM/rQT8ZBCVqeG', 'Prasad More (EMT)',           'Golf-235 (BLS Unit)',     'amb-235', 'prasad.more@crisiscare.in'),
('PARA-134', '$2b$12$ashv3XcnuBHcPVRebGUeq.sZAsTGoBFBN3Fl8QnrM/rQT8ZBCVqeG', 'Ashwini Khedkar (Paramedic)', 'Hotel-343 (ALS Unit)',    'amb-343', 'ashwini.khedkar@crisiscare.in'),
('PARA-135', '$2b$12$2VUapdTbeoNB4hFuZnOjV.sw0f2NXehcZoJ5E/ls8/2GvsY3rx.g.', 'Dhananjay Deshpande (EMT)',   'India-160 (BLS Unit)',    'amb-160', 'dhananjay.deshpande@crisiscare.in'),
('PARA-136', '$2b$12$2VUapdTbeoNB4hFuZnOjV.sw0f2NXehcZoJ5E/ls8/2GvsY3rx.g.', 'Rupali Thakur (Paramedic)',   'Juliet-464 (ALS Unit)',   'amb-464', 'rupali.thakur@crisiscare.in'),
('PARA-137', '$2b$12$ashv3XcnuBHcPVRebGUeq.sZAsTGoBFBN3Fl8QnrM/rQT8ZBCVqeG', 'Sandeep Apte (EMT)',          'Kilo-239 (BLS Unit)',     'amb-239', 'sandeep.apte@crisiscare.in'),
('PARA-138', '$2b$12$ashv3XcnuBHcPVRebGUeq.sZAsTGoBFBN3Fl8QnrM/rQT8ZBCVqeG', 'Madhuri Pise (Paramedic)',    'Lima-347 (ALS Unit)',     'amb-347', 'madhuri.pise@crisiscare.in'),
('PARA-139', '$2b$12$2VUapdTbeoNB4hFuZnOjV.sw0f2NXehcZoJ5E/ls8/2GvsY3rx.g.', 'Vinay Kale (EMT)',            'Mike-166 (BLS Unit)',     'amb-166', 'vinay.kale@crisiscare.in'),
('PARA-140', '$2b$12$2VUapdTbeoNB4hFuZnOjV.sw0f2NXehcZoJ5E/ls8/2GvsY3rx.g.', 'Archana Lad (Paramedic)',     'November-470 (ALS Unit)', 'amb-470', 'archana.lad@crisiscare.in'),
('PARA-141', '$2b$12$ashv3XcnuBHcPVRebGUeq.sZAsTGoBFBN3Fl8QnrM/rQT8ZBCVqeG', 'Kedar Munshi (EMT)',          'Oscar-243 (BLS Unit)',    'amb-243', 'kedar.munshi@crisiscare.in'),
('PARA-142', '$2b$12$ashv3XcnuBHcPVRebGUeq.sZAsTGoBFBN3Fl8QnrM/rQT8ZBCVqeG', 'Smita Funde (Paramedic)',     'Papa-351 (ALS Unit)',     'amb-351', 'smita.funde@crisiscare.in'),
('PARA-143', '$2b$12$2VUapdTbeoNB4hFuZnOjV.sw0f2NXehcZoJ5E/ls8/2GvsY3rx.g.', 'Vishal Damle (EMT)',          'Quebec-172 (BLS Unit)',   'amb-172', 'vishal.damle@crisiscare.in'),
('PARA-144', '$2b$12$2VUapdTbeoNB4hFuZnOjV.sw0f2NXehcZoJ5E/ls8/2GvsY3rx.g.', 'Tejashri Lokare (Paramedic)', 'Romeo-476 (ALS Unit)',    'amb-476', 'tejashri.lokare@crisiscare.in'),
('PARA-145', '$2b$12$ashv3XcnuBHcPVRebGUeq.sZAsTGoBFBN3Fl8QnrM/rQT8ZBCVqeG', 'Rahul Bagul (EMT)',           'Sierra-247 (BLS Unit)',   'amb-247', 'rahul.bagul@crisiscare.in'),
('PARA-146', '$2b$12$ashv3XcnuBHcPVRebGUeq.sZAsTGoBFBN3Fl8QnrM/rQT8ZBCVqeG', 'Manali Wadekar (Paramedic)',  'Tango-355 (ALS Unit)',    'amb-355', 'manali.wadekar@crisiscare.in'),
('PARA-147', '$2b$12$2VUapdTbeoNB4hFuZnOjV.sw0f2NXehcZoJ5E/ls8/2GvsY3rx.g.', 'Siddhesh Tambe (EMT)',        'Uniform-178 (BLS Unit)',  'amb-178', 'siddhesh.tambe@crisiscare.in'),
('PARA-148', '$2b$12$2VUapdTbeoNB4hFuZnOjV.sw0f2NXehcZoJ5E/ls8/2GvsY3rx.g.', 'Harshada Gunjal (Paramedic)', 'Victor-482 (ALS Unit)',   'amb-482', 'harshada.gunjal@crisiscare.in'),
('PARA-149', '$2b$12$ashv3XcnuBHcPVRebGUeq.sZAsTGoBFBN3Fl8QnrM/rQT8ZBCVqeG', 'Yashraj Kshirsagar (EMT)',    'Whiskey-251 (BLS Unit)',  'amb-251', 'yashraj.kshirsagar@crisiscare.in'),
('PARA-150', '$2b$12$ashv3XcnuBHcPVRebGUeq.sZAsTGoBFBN3Fl8QnrM/rQT8ZBCVqeG', 'Rutuja Bhalerao (Paramedic)', 'Xray-359 (ALS Unit)',     'amb-359', 'rutuja.bhalerao@crisiscare.in'),
('PARA-409', '$2b$12$ashv3XcnuBHcPVRebGUeq.sZAsTGoBFBN3Fl8QnrM/rQT8ZBCVqeG', 'Dr. Ananya Roy (Paramedic Lead)', 'Delta-101 (ALS Unit)', 'amb-101', 'ananya.roy@crisiscare.in')
ON CONFLICT (badge_id) DO NOTHING;
