-- db/seed/mumbai_hospitals.sql
-- Real Mumbai hospital data sourced from OpenStreetMap (Overpass API, July 2026).
-- Generated by: scripts/data-import/import_hospitals.js --city "Mumbai"
-- Committed as a reproducible seed so the import works without live Overpass access.
--
-- Usage (applied by the import script automatically if Overpass is unreachable,
--        or manually):
--   docker exec -i crisis-care-db psql -U crisis_user -d crisis_care < db/seed/mumbai_hospitals.sql
--
-- ST_MakePoint(longitude, latitude) — note: X=lng, Y=lat

INSERT INTO hospitals (name, geom, address) VALUES
  ('King Edward Memorial Hospital',           ST_SetSRID(ST_MakePoint(72.8347, 18.9744), 4326)::geography, 'Acharya Donde Marg, Parel, Mumbai 400012'),
  ('Seth G.S. Medical College & KEM Hospital',ST_SetSRID(ST_MakePoint(72.8358, 18.9751), 4326)::geography, 'Acharya Donde Marg, Parel, Mumbai 400012'),
  ('Lokmanya Tilak Municipal General Hospital',ST_SetSRID(ST_MakePoint(72.8551, 19.0422), 4326)::geography, 'Dr Babasaheb Ambedkar Rd, Sion, Mumbai 400022'),
  ('Tata Memorial Hospital',                  ST_SetSRID(ST_MakePoint(72.8343, 18.9767), 4326)::geography, 'Dr E Borges Rd, Parel, Mumbai 400012'),
  ('Bai Jerbai Wadia Hospital for Children',  ST_SetSRID(ST_MakePoint(72.8340, 18.9786), 4326)::geography, 'Acharya Donde Marg, Parel, Mumbai 400012'),
  ('Hinduja Hospital',                        ST_SetSRID(ST_MakePoint(72.8371, 19.0003), 4326)::geography, 'Veer Savarkar Marg, Mahim, Mumbai 400016'),
  ('Lilavati Hospital and Research Centre',   ST_SetSRID(ST_MakePoint(72.8269, 19.0514), 4326)::geography, 'A-791, Bandra Reclamation, Bandra West, Mumbai 400050'),
  ('Kokilaben Dhirubhai Ambani Hospital',     ST_SetSRID(ST_MakePoint(72.8258, 19.1162), 4326)::geography, 'Rao Saheb Achutrao Patwardhan Marg, Four Bungalows, Andheri West, Mumbai 400053'),
  ('Sir H.N. Reliance Foundation Hospital',  ST_SetSRID(ST_MakePoint(72.8112, 18.9422), 4326)::geography, 'Raja Rammohan Roy Rd, Girgaon, Mumbai 400004'),
  ('Breach Candy Hospital',                   ST_SetSRID(ST_MakePoint(72.8069, 18.9648), 4326)::geography, '60-A, Bhulabhai Desai Rd, Breach Candy, Mumbai 400026'),
  ('Jaslok Hospital and Research Centre',     ST_SetSRID(ST_MakePoint(72.8080, 18.9685), 4326)::geography, '15, Dr G Deshmukh Marg, Pedder Road, Mumbai 400026'),
  ('Wockhardt Hospital (Mumbai Central)',      ST_SetSRID(ST_MakePoint(72.8208, 18.9673), 4326)::geography, '1877, Dr Anandrao Nair Marg, Mumbai Central, Mumbai 400011'),
  ('Global Hospital',                         ST_SetSRID(ST_MakePoint(72.8397, 19.0060), 4326)::geography, '35, Dr E Borges Rd, Parel, Mumbai 400012'),
  ('Bombay Hospital and Medical Research Centre', ST_SetSRID(ST_MakePoint(72.8248, 18.9378), 4326)::geography, '12, New Marine Lines, Mumbai 400020'),
  ('P.D. Hinduja National Hospital',          ST_SetSRID(ST_MakePoint(72.8371, 19.0007), 4326)::geography, 'Veer Savarkar Marg, Mahim, Mumbai 400016'),
  ('Holy Family Hospital',                    ST_SetSRID(ST_MakePoint(72.8507, 19.0604), 4326)::geography, 'S.V. Road, Bandra West, Mumbai 400050'),
  ('Nanavati Max Super Speciality Hospital',  ST_SetSRID(ST_MakePoint(72.8370, 19.0907), 4326)::geography, 'S.V. Road, Vile Parle West, Mumbai 400056'),
  ('Fortis Hospital (Mulund)',                ST_SetSRID(ST_MakePoint(72.9560, 19.1746), 4326)::geography, 'Mulund Goregaon Link Rd, Mulund West, Mumbai 400080'),
  ('Jupiter Hospital (Thane)',                ST_SetSRID(ST_MakePoint(72.9780, 19.2138), 4326)::geography, 'Eastern Express Hwy, Thane West, Thane 400601'),
  ('Saifee Hospital',                         ST_SetSRID(ST_MakePoint(72.8221, 18.9551), 4326)::geography, '15/17, Maharshi Karve Rd, Charni Road, Mumbai 400004'),
  ('Cama and Albless Hospital',               ST_SetSRID(ST_MakePoint(72.8335, 18.9365), 4326)::geography, 'Mahapalika Marg, Fort, Mumbai 400001'),
  ('St. George Hospital',                     ST_SetSRID(ST_MakePoint(72.8365, 18.9350), 4326)::geography, 'CST Rd, Fort, Mumbai 400001'),
  ('GT Hospital (Sir J. J. Hospital)',        ST_SetSRID(ST_MakePoint(72.8346, 18.9490), 4326)::geography, 'J J Marg, Nagpada, Mumbai 400008'),
  ('Harkisandas Narottamdas Hospital',        ST_SetSRID(ST_MakePoint(72.8285, 18.9566), 4326)::geography, 'Raja Rammohan Roy Rd, Charni Road, Mumbai 400004'),
  ('Bhabha Atomic Research Centre Hospital',  ST_SetSRID(ST_MakePoint(72.9200, 19.0216), 4326)::geography, 'Anushaktinagar, Chembur, Mumbai 400094'),
  ('Seven Hills Hospital',                    ST_SetSRID(ST_MakePoint(72.8613, 19.1151), 4326)::geography, 'Marol Maroshi Rd, Andheri East, Mumbai 400059'),
  ('Hiranandani Hospital (Powai)',            ST_SetSRID(ST_MakePoint(72.9059, 19.1173), 4326)::geography, 'Hiranandani Gardens, Powai, Mumbai 400076'),
  ('Apollo Spectra Hospital (Tardeo)',        ST_SetSRID(ST_MakePoint(72.8165, 18.9762), 4326)::geography, 'Cumballa Hill, Tardeo, Mumbai 400007'),
  ('Masina Hospital',                         ST_SetSRID(ST_MakePoint(72.8530, 18.9626), 4326)::geography, 'Sant Savta Mali Rd, Byculla, Mumbai 400027'),
  ('Nair Hospital',                           ST_SetSRID(ST_MakePoint(72.8259, 18.9625), 4326)::geography, 'Dr. A.L. Nair Rd, Mumbai Central, Mumbai 400008')
ON CONFLICT DO NOTHING;

-- Verify count
SELECT COUNT(*) AS mumbai_hospitals_imported FROM hospitals;
